[phases.setup]
nixpkgs_archive = "nixos-24.11"
pkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
command = "node /app/.output/server/index.mjs"
